-- AULA 11/07
-- COMANDOS BÁSICOS
-- REGRA SQL: MAIUSCULO NOS COMANDOS
-- MINUSCULO EM OUTROS VALORES

SHOW DATABASES; -- LISTA TODOS OS BANCOS DISPONÍVEIS

CREATE DATABASE empresa_db; -- CRIA UM BANCO DE DADOS COM O NOME ESPECIFICADO

USE empresa_db; -- SELECIONA O BANCO DESEJADO PARA USAR

SHOW TABLES; -- MOSTRA AS TABELAS DO BANCO SELECIONADO

DROP DATABASE empresa_db; -- APAGA O BANCO ESPECIFICADO

CREATE TABLE departamento( -- CRIAR TABELA E AS COLUNAS
	idDepartamento INTEGER PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(200),
    descricao VARCHAR(200)
);

INSERT INTO departamento VALUES (NULL, "RH", "Recursos Humanos");

-- TIPOS DE DADOS
-- INT / INTEGER = ATÉ 2BILHOES
-- BIGINT = ATÉ 9QUINTILHOES
-- DECIMAL = VALORES DECIMAIS EXATOS
-- FLOAT = ATÉ 7 CASAS PRECISÃO
-- DOUBLE = ATÉ 15 CASAS DE PRECISÃO
-- VARCHAR = STRING
-- TEXT = TEXTOS MUITO LONGOS
-- DATE = FORMATO YYYY-MM-DD
-- TIME = FORMATO hh:mm:ss
-- DATETIME = FORMATO YYYY-MM-DD hh:mm:ss
-- BLOB = ARQUIVOS (BINARY LARGE OBJECT)


CREATE TABLE colaborador(
	idColaborador INTEGER PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(200) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    salario DECIMAL(8, 2) NOT NULL,
    telefone VARCHAR(20) UNIQUE NOT NULL,
    dataNascimento DATE NOT NULL,
    fkDepartamento INTEGER NOT NULL,
    FOREIGN KEY (fkDepartamento) -- COLUNA QUE SERÁ A CHAVE ESTRANGEIRA
    REFERENCES departamento(idDepartamento) -- CHAVE PRIMÁRIA DA OUTRA TABELA
);

CREATE TABLE endereco(
	idEndereco INTEGER PRIMARY KEY AUTO_INCREMENT,
    cidade VARCHAR(30) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    rua VARCHAR(40) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(40) DEFAULT("Sem Complemento"),
    fkColaborador UNIQUE INTEGER NOT NULL,
    FOREIGN KEY (fkColaborador)
    REFERENCES colaborador(idColaborador)
);

