USE LOJA_DB;

-- JUNÇÃO

SELECT V.NOME, V.EMAIL, E.UF, E.CIDADE
FROM VENDEDOR V
	JOIN ENDERECO E
	ON V.IDVENDEDOR = E.FKVENDEDOR
WHERE UF = 'RJ';

-- Q1: JUNTE PRODUTO + CATEGORA;
SELECT P.NOME AS PRODUTO, P.PRECO, C.NOME AS CATEGORIA
FROM PRODUTO P
	JOIN CATEGORIA C
	ON P.FKCATEGORIA = C.IDCATEGORIA
WHERE C.NOME = "Jogos";

-- Q2: JUNTE PRODUTO + VENDEDOR
SELECT V.NOME VENDEDOR, P.NOME PRODUTO
FROM PRODUTO P
	JOIN VENDEDOR V
    ON V.IDVENDEDOR = P.FKVENDEDOR
WHERE YEAR(V.DATANASCIMENTO) < 1991; 

-- Q3: JUNTE PRODUTO + VENDEDOR + ENDERECO
SELECT V.NOME VENDEDOR, P.NOME PRODUTO, V.DATANASCIMENTO, E.UF, E.CIDADE
FROM PRODUTO P
	JOIN VENDEDOR V
    ON V.IDVENDEDOR = P.FKVENDEDOR
    JOIN ENDERECO E
    ON V.IDVENDEDOR = E.FKVENDEDOR; 